optimize fetch order by id
hngx-org/zuriportfolio-commander-backend pull request #26
Opened 2023-10-12 03:44 UTC by ochosteve08

you can check this one that was used for the previous cohort

# Fixes Issue/Linear Ticket

> This could be an existing issue or a linear ticket
>
> - Github Issue Example: My PR Closes #{ISSUE}
> - Linear Ticket Example: Fixes ID-#{ISSUE}

# Changes proposed

> Talk about the things you did eg. files changes, dependencies installed e.t.c

# Check List (Check all the applicable boxes)

:rotating_light:Please review the [style guide for contributing](add link here) and [guidelines for contributing](add link here) to this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **main branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/ Videos

2023-10-12 05:58 UTC, Benrobo requested changes
Your implementation is wrong... look at the design and see the data we need to fetch all orders, i'll prefer you look for away to join order and order_item table to get necessary info.

secondly, why use `return res.status(404).json({ message: 'Order not found' });` when you have `this.error()` within each controller? please fix this...

2023-10-12 07:50 UTC, ochosteve08 commented
error handler fixed, let me also point that i am not working on fetch all orders by fetch orders by id.

2023-10-12 11:52 UTC, Benrobo commented
resolve your conflict

2023-10-13 15:29 UTC, edahmitchel approved these changes

2023-10-13 15:31 UTC, edahmitchel approved these changes

2023-10-13 15:38 UTC, merged