Added the endpoint to get all Shops
hngx-org/zuriportfolio-commander-backend pull request #34
Opened 2023-10-12 13:49 UTC by Oludayo20

you can check this one that was used for the previous cohort

# Fixes Issue/Linear Ticket

> This could be an existing issue or a linear ticket
>
> - Github Issue Example: My PR Closes Shops
> - Linear Ticket Example: Fixes ID-COM-30

# Changes proposed

I created an endpoint and route that encapsulate the logic for retrieving a list of shops from a database using Prisma. This function handles both success and error scenarios, sending appropriate responses back to the client via the provided Response object. And also wrote the swagger doc.

# Check List (Check all the applicable boxes)

:rotating_light:Please review the [style guide for contributing](add link here) and [guidelines for contributing](add link here) to this repository.

- [V] My code follows the code style of this project.
- [V] This PR does not contain plagiarized content.
- [V] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **main branch** (left side).
- [V] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [V] I am only making changes to files I was requested to.

![image](https://github.com/hngx-org/zuriportfolio-commander-backend/assets/66706725/d77d3678-6fd9-40f3-916b-739d797f3fa6)

2023-10-12 16:46 UTC, Benrobo commented
fix your merge conflict

2023-10-12 17:20 UTC, Oludayo20 commented
Done

2023-10-12 22:08 UTC, Benrobo commented
resolve conflict please!

2023-10-13 06:54 UTC, Oludayo20 commented
Done

2023-10-13 07:51 UTC, Benrobo requested changes

2023-10-13 07:51 UTC, Benrobo commented on src/controller/shop.controller.ts
> +    const shops = await prisma.shop.findMany();
this is wrong.. you can't return all shops available on the app.. you only need to return shops created by the user.

2023-10-13 07:51 UTC, Benrobo commented on src/controller/shop.controller.ts
> +    if (shops.length > 0) {
secondly, you dont need to check if it empty or not, if the shop is empty, an empty array would be returned and the frontend devs can decide to show a message based on that.

2023-10-13 07:51 UTC, Benrobo commented on src/controller/shop.controller.ts
> +      this.error(res, '--shops-notfound', 'Shops not found', 404);
sending error isn't ok as this operation isn't an error, it only means the user has no shop, so pls change all this..

2023-10-13 09:47 UTC, closed without merging