Feat/orderCount by timeframe
hngx-org/zuriportfolio-commander-backend pull request #45
Opened 2023-10-12 20:46 UTC by ceasar28

you can check this one that was used for the previous cohort

# Fixes Issue/Linear Ticket
https://linear.app/zuri-project-backend/issue/COM-26/api-for-getting-orders-count-in-a-timeframe

> This could be an existing issue or a linear ticket
>
> - Github Issue Example: My PR Closes #{ISSUE}
> - Linear Ticket Example: Fixes ID-#{ISSUE}

# Changes proposed

> Talk about the things you did eg. files changes, dependencies installed e.t.c
Added endpoint  with query params  to get the count of orders made with a timeframe like: today, yesterday, one-week-ago and two-weeks-ago, this will help in analytical purposes

# Check List (Check all the applicable boxes)

:rotating_light:Please review the [style guide for contributing](add link here) and [guidelines for contributing](add link here) to this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **main branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/ Videos

2023-10-12 22:02 UTC, Benrobo commented
resolve conflict

2023-10-12 23:45 UTC, Benrobo commented
resolve your conflict

2023-10-13 01:09 UTC, ceasar28 commented
Boss I have resolved the conflicts

2023-10-13 07:18 UTC, ceasar28 commented
The more conflicts keeps coming up after merging other PRs

2023-10-13 08:52 UTC, AirZED approved these changes

2023-10-13 08:52 UTC, merged

2023-10-13 08:53 UTC, Benrobo requested changes
your code can't be accepted.. you literally wanna stop the server from running..

pull and update with the dev branch

2023-10-13 08:53 UTC, Benrobo commented on src/controller/discount.controller.ts
> +//     const validateSchema = createDiscountSchema.validate(req.body);
Why would you comment out a code someone worked on and add your yarn-error.log? why!!! .. do you wanna break the feature someone has been implementing

2023-10-14 18:08 UTC, ceasar28 commented
> your code can't be accepted..
> 
> pull and update with the dev branch

Done .