Added '/api/revenues?timeframe=today'
hngx-org/zuriportfolio-commander-backend pull request #46
Opened 2023-10-12 21:34 UTC by EzeibekweEmma

# Fixes Issue/Linear Ticket

> This could be an existing issue or a linear ticket
>
> - Linear Ticket Example: Fixes ID-#{COM-39}

# Changes proposed

> Add 'GET /api/revenues?timeframe=today' route for fetching today's revenue data, with parameter validation and success handling.

# Check List (Check all the applicable boxes)

:rotating_light:Please review the [style guide for contributing](add link here) and [guidelines for contributing](add link here) to this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **main branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/ Videos

2023-10-12 23:56 UTC, Benrobo requested changes

2023-10-12 23:56 UTC, Benrobo commented on src/routes/revenue.route.ts
> +    this.router.get(
why did you change the base `path` when you can easily add s at the end of base path`${this.path}s` ? please revert it back as all other endpoint without an `s` depends on it.

2023-10-12 23:56 UTC, Benrobo commented on src/routes/revenue.route.ts
>    path = '/revenues';
change this back to `revenue`

2023-10-13 04:29 UTC, EzeibekweEmma commented on src/routes/revenue.route.ts
>    path = '/revenues';
done

2023-10-13 07:53 UTC, Benrobo approved these changes
ok

2023-10-13 07:53 UTC, merged